[package]
name = "stderr"
version = "0.7.1"
authors = ["biluohc <biluohc@outlook.com>"]

description = "A library that using macro to write to io::stderr() like print!()/println!()."

documentation = "https://docs.rs/stderr/"
# homepage = "..."
repository = "https://github.com/biluohc/stderr"

readme = "readme.md"

keywords = ["err","errst","log","debug","print"]

license = "MIT"

[dependencies]
time = "0.1"
# stderr= { path = "/home/viw/Documents/git/github/stderr" }

[[test]]
name ="main"
path="tests/main.rs"