[package]
name = "stderr"
version = "0.5.0"
authors = ["biluohc <biluohc@outlook.com>"]

description = "A library that using macro to write io::stderr() for error or io::stdout() for log optional like print!/println!."

# documentation = "..."
# homepage = "..."
repository = "https://github.com/biluohc/stderr"

readme = "readme.md"

keywords = ["err","errst","log","debug","print"]

license = "MIT"

[dependencies]

[[test]]
name ="main"
path="tests/main.rs"