[package]
name = "stderr"
version = "0.2.1"
authors = ["biluohc <biluohc@outlook.com>"]

# A short blurb about the package. This is not rendered in any format when
# uploaded to crates.io (aka this is not markdown).
description = "A library that using macro to write to io::stderr() like print!/println!."

# These URLs point to more information about the repository.
# documentation = "..."
# homepage = "..."
repository = "https://github.com/biluohc/stderr"

# This points to a file in the repository (relative to this `Cargo.toml`). The
# contents of this file are stored and indexed in the registry.
readme = "readme.md"

keywords = ["stderr","err","errst","macro","print"]

license = "MIT"

[dependencies]

